In [22]:
from Bio import Entrez
import pandas as pd

In [21]:
Entrez.email = "hekaybob5522@gmail.com"

ETL PIPELINE

In [16]:
from src.data_collection import search_pubmed
pmids = search_pubmed('lung cancer biomarker', retmax=100)
print(len(pmids))
print(pmids)

100
['42324360', '42323710', '42323489', '42322507', '42322411', '42322174', '42321804', '42321301', '42320986', '42320983', '42320980', '42320171', '42318986', '42318462', '42318460', '42318346', '42317372', '42317239', '42315853', '42315819', '42314966', '42314881', '42314262', '42314092', '42314086', '42313838', '42313501', '42313297', '42312951', '42312823', '42312604', '42311664', '42311313', '42311064', '42310804', '42310642', '42310334', '42310302', '42310154', '42310061', '42308637', '42308329', '42308255', '42307755', '42307064', '42306740', '42306733', '42306692', '42306683', '42306682', '42305536', '42305529', '42305511', '42304747', '42304496', '42304312', '42304141', '42303867', '42303760', '42303501', '42303407', '42303257', '42303143', '42303101', '42302911', '42302749', '42302339', '42302215', '42301942', '42301654', '42299588', '42299458', '42299414', '42298893', '42297835', '42296718', '42296679', '42296229', '42296148', '42295485', '42294312', '42294284', '42293764', '42293334', '42292949', '42292701', '42292485', '42292481', '42292412', '42292366', '42292238', '42291403', '42291366', '42291363', '42291361', '42291360', '42291356', '42291350', '42291348', '42291343']

In [23]:
from src.data_collection import fetch_papers
fetch_papers(pmids)

,PMID,Title,Abstract,Year
0,42324360,A decade of progress in small-cell lung cancer...,Small-cell lung cancer (SCLC) accounts for 13-...,2026
1,42323710,Extracellular vesicles as diagnostic and progn...,Non-small cell lung cancer (NSCLC) remains the...,2026
2,42323489,Who Gets Left Out of Precision Oncology? Real-...,Precision oncology in non-small cell lung canc...,2026
3,42322507,Pan-cancer integrative profiling of immune-rel...,Long non-coding RNAs (lncRNAs) have been widel...,2026
4,42322411,Single-cell and multi-omics integration deline...,"Gene-wise intratumor heterogeneity (ITH), defi...",2026
...,...,...,...,...
95,42291360,"CEACAM5 as a biomarker of semi-solid, lepidic ...",Carcinoembryonic antigen-related cell adhesion...,2026
96,42291356,<i>ZNF528</i> as a novel driver of metastasis ...,Non-small cell lung cancer (NSCLC) remains a l...,2026
97,42291350,Advances in translational lung cancer research...,"By 2025, lung cancer translational research in...",2026
98,42291348,Major histocompatibility complex II serves as ...,Pulmonary sarcomatoid carcinoma (PSC) is a rar...,2026
99,42291343,Elevated baseline C-reactive protein predicts ...,Systemic inflammation has been implicated in c...,2026

In [25]:
df = pd.DataFrame(fetch_papers(pmids))

In [26]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   PMID      100 non-null    str
 1   Title     100 non-null    str
 2   Abstract  100 non-null    str
 3   Year      91 non-null     str
dtypes: str(4)
memory usage: 203.0 KB

PMID        0
Title       0
Abstract    0
Year        9
dtype: int64

In [26]:
df.shape

(100, 4)

In [28]:
df.head()

,PMID,Title,Abstract,Year
0,42324360,A decade of progress in small-cell lung cancer...,Small-cell lung cancer (SCLC) accounts for 13-...,2026
1,42323710,Extracellular vesicles as diagnostic and progn...,Non-small cell lung cancer (NSCLC) remains the...,2026
2,42323489,Who Gets Left Out of Precision Oncology? Real-...,Precision oncology in non-small cell lung canc...,2026
3,42322507,Pan-cancer integrative profiling of immune-rel...,Long non-coding RNAs (lncRNAs) have been widel...,2026
4,42322411,Single-cell and multi-omics integration deline...,"Gene-wise intratumor heterogeneity (ITH), defi...",2026

In [27]:
df.to_csv("../data/raw/pubmed_papers.csv", index = False)