In [1]:
from Bio import Entrez
import pandas as pd

print("Loaded successfully")

Loaded successfully

In [2]:
Entrez.email = "hekaybob5522@gmail.com"

In [3]:
search_term = 'lung cancer biomaker'

handle = Entrez.esearch(
    db='pubmed',
    term= search_term,
    retmax = 10
)

record = Entrez.read(handle)

pmids = record['IdList']
print(f"Found {(len(pmids))} papers")
print(pmids)

Found 10 papers
['42000796', '40057669', '39609902', '38501000', '38456253', '38294307', '38126740', '36306573', '35923467', '35047506']

In [4]:
paper_id = pmids[0]

handle = Entrez.efetch(
    db='pubmed',
    id = paper_id,
    rettype = 'abstract',
    retmode = 'xml'
)

paper = Entrez.read(handle)
paper

{'PubmedBookArticle': [], 'PubmedArticle': [{'MedlineCitation': DictElement({'OtherAbstract': [], 'CitationSubset': ['IM'], 'GeneralNote': [], 'SpaceFlightMission': [], 'OtherID': [], 'InvestigatorList': [], 'KeywordList': [ListElement([StringElement('16S rRNA sequencing', attributes={'MajorTopicYN': 'N'}), StringElement('Biomakers', attributes={'MajorTopicYN': 'N'}), StringElement('Gut microbiome', attributes={'MajorTopicYN': 'N'}), StringElement('Lung cancer', attributes={'MajorTopicYN': 'N'})], attributes={'Owner': 'NOTNLM'})], 'PMID': StringElement('42000796', attributes={'Version': '1'}), 'DateRevised': {'Year': '2026', 'Month': '04', 'Day': '18'}, 'Article': DictElement({'ELocationID': [StringElement('10.1038/s41598-026-48560-w', attributes={'EIdType': 'doi', 'ValidYN': 'Y'})], 'Language': ['eng'], 'ArticleDate': [DictElement({'Year': '2026', 'Month': '04', 'Day': '18'}, attributes={'DateType': 'Electronic'})], 'Journal': {'ISSN': StringElement('2045-2322', attributes={'IssnType': 'Electronic'}), 'JournalIssue': DictElement({'PubDate': {'Year': '2026', 'Month': 'Apr', 'Day': '18'}}, attributes={'CitedMedium': 'Internet'}), 'Title': 'Scientific reports', 'ISOAbbreviation': 'Sci Rep'}, 'ArticleTitle': 'Exploring the characteristics of gut microbiome changes in lung cancer patients and healthy controls.', 'Abstract': {'AbstractText': ['Lung cancer is among the most prevalent and lethal malignant neoplasms worldwide. Although the role of the pulmonary microbiome in the pathogenesis of lung cancer has been examined, the structure, diversity, and composition of the gut microbiome in lung cancer remain largely unclear. The present study is chiefly concerned with the analysis of the characteristics and alterations of the gut microbiome in lung cancer patients and healthy individuals, and with the exploration of potential characteristic gut microbiome in lung cancer patients. Stool samples were collected from 40 patients with lung cancer and 20 healthy controls at the Lung Cancer Center of West China Hospital, Sichuan University. The samples were analysed using 16S rRNA gene amplicon sequencing to investigate differences in the relative and absolute abundance, diversity, and functionality of the gut microbiome between the two groups. The predominant gut microbiome communities in lung cancer patients and healthy controls were found to comprise Bacteroidetes, Firmicutes, Proteobacteria, and Actinobacteria. The F/B (Firmicutes/Bacteroidetes) ratio in the lung cancer group (0.73) was lower than that in the healthy control group (0.96). We found that there was no significant difference in α-diversity between LC patients and the control group (p\u2009>\u20090.05), whereas β-diversity of the gut microbiome revealed differences in microbial community structure between the patient and control groups (stress\u2009<\u20090.2). The healthy controls exhibited higher abundances of Bacteroidetes and Firmicutes as dominant bacterial groups, whereas the characteristic bacterial groups in lung cancer patients were the Ruminococcus_gnavus_group and the Prevotellaceae NK3B31 group. Studies have demonstrated that the gut microbiome of patients with lung cancer patients undergoes changes, and characteristic gut microbiome profiles may serve as potential diagnostic markers for lung cancer. Furthermore, we have revealed that impairments in normal gut microbiome function may be associated with the development and progression of lung cancer, providing valuable insights for the early prevention, diagnosis, and targeted intervention of lung cancer.'], 'CopyrightInformation': '© 2026. The Author(s).'}, 'AuthorList': ListElement([DictElement({'AffiliationInfo': [{'Identifier': [], 'Affiliation': "Health Management Center, General Practice Medical Center, West China Hospital, Sichuan University, Chengdu, People's Republic of China."}], 'Identifier': [], 'LastName': 'Xu', 'ForeName': 'Peisheng', 'Initials': 'P'}, attributes={'ValidYN': 'Y', 'EqualContrib': 'Y'}), DictElement({'AffiliationInfo': [{'Identifier': [], 'Affiliation': "Department of Laboratory Medicine, West China Hospital, Sichuan University, Chengdu, People's Republic of China."}], 'Identifier': [], 'LastName': 'Chen', 'ForeName': 'Juan', 'Initials': 'J'}, attributes={'ValidYN': 'Y', 'EqualContrib': 'Y'}), DictElement({'AffiliationInfo': [{'Identifier': [], 'Affiliation': "Department of Laboratory Medicine, West China Hospital, Sichuan University, Chengdu, People's Republic of China."}], 'Identifier': [], 'LastName': 'Lu', 'ForeName': 'Xingbing', 'Initials': 'X'}, attributes={'ValidYN': 'Y'}), DictElement({'AffiliationInfo': [{'Identifier': [], 'Affiliation': "Department of Ophthalmology, West China Hospital, Sichuan University, Guoxue Lane37, Chengdu, Sichuan, People's Republic of China. 401690191@qq.com."}, {'Identifier': [], 'Affiliation': "West China School of Nursing, Sichuan University, Chengdu, People's Republic of China. 401690191@qq.com."}], 'Identifier': [], 'LastName': 'Luo', 'ForeName': 'Hongmei', 'Initials': 'H'}, attributes={'ValidYN': 'Y'})], attributes={'CompleteYN': 'Y'}), 'PublicationTypeList': [StringElement('Journal Article', attributes={'UI': 'D016428'})]}, attributes={'PubModel': 'Print-Electronic'}), 'MedlineJournalInfo': {'Country': 'England', 'MedlineTA': 'Sci Rep', 'NlmUniqueID': '101563288', 'ISSNLinking': '2045-2322'}, 'CoiStatement': 'Declarations. Competing interests: The authors declare no competing interests. Ethics statement: Fecal samples were collected in this research without any medical expense or suffering by the subjects, and the results were used for scientific research purposes. We declare that none of the authors have any conflicts of interest or financial ties to disclose. The protocol was approved by the Ethics Review Committee of West China Hospital, Sichuan University (reference: 2021-1120, 04/11/2021). All subjects gave written informed consent in accordance with the Declaration of Helsinki. The rights of the subjects were adequately protected, and there was no potential risk to the subjects. Informed consent was obtained from all individual participants included in the study.'}, attributes={'Status': 'Publisher', 'Owner': 'NLM'}), 'PubmedData': {'ReferenceList': [{'Reference': [{'Citation': 'Potter, A. L., Sequist, L. V. & Yang, C. J. Lung cancer screening saves lives, but could save so many more. JAMA https://doi.org/10.1001/jama.2025.23244 (2025).'}, {'Citation': 'Bray, F. et al. Global cancer statistics 2022: GLOBOCAN estimates of incidence and mortality worldwide for 36 cancers in 185 countries. CA Cancer J. Clin. 74(3), 229–263. https://doi.org/10.3322/caac.21834 (2024).'}, {'Citation': 'Ettinger, D. S. et al. Non-small cell lung cancer, version 3.2022, NCCN clinical practice guidelines in oncology. J. Natl. Compr. Cancer Netw. 20(5), 497–530. https://doi.org/10.6004/jnccn.2022.0025 (2022).'}, {'Citation': 'Leiter, A., Veluswamy, R. R. & Wisnivesky, J. P. The global burden of lung cancer: Current status and future trends. Nat. Rev. Clin. Oncol. 20(9), 624–639. https://doi.org/10.1038/s41571-023-00798-3 (2023).'}, {'Citation': 'Murphy, C. et al. Lung cancer in nonsmoking individuals: A review. JAMA https://doi.org/10.1001/jama.2025.17695 (2025).'}, {'Citation': 'Brandi, G. & Frega, G. Microbiota: Overview and implication in immunotherapy-based cancer treatments. Int. J. Mol. Sci. https://doi.org/10.3390/ijms20112699 (2019).'}, {'Citation': 'Cruz, M. S., Tintelnot, J. & Gagliani, N. Roles of microbiota in pancreatic cancer development and treatment. Gut Microbes 16(1), 2320280. https://doi.org/10.1080/19490976.2024.2320280 (2024).'}, {'Citation': 'Wang, J. et al. Microbiome-metabolome dysbiosis of bronchoalveolar lavage fluid of lung cancer patients. Front. Microbiol. 16, 1669172. https://doi.org/10.3389/fmicb.2025.1669172 (2025).'}, {'Citation': 'Baranova, E. et al. Sputum microbiome composition in patients with squamous cell lung carcinoma. Life https://doi.org/10.3390/life12091365 (2022).'}, {'Citation': 'Geller, L. T. & Straussman, R. Intratumoral bacteria may elicit chemoresistance by metabolizing anticancer agents. Mol. Cell. Oncol. 5(1), e1405139. https://doi.org/10.1080/23723556.2017.1405139 (2018).'}, {'Citation': 'Riquelme, E. et al. Tumor microbiome diversity and composition influence pancreatic cancer outcomes. Cell 178(4), 795–806. https://doi.org/10.1016/j.cell.2019.07.008 (2019).'}, {'Citation': 'Zheng, Y. et al. Specific gut microbiome signature predicts the early-stage lung cancer. Gut Microbes 11(4), 1030–1042. https://doi.org/10.1080/19490976.2020.1737487 (2020).'}, {'Citation': 'Jin, Y. et al. The diversity of gut microbiome is associated with favorable responses to anti-programmed death 1 immunotherapy in Chinese patients with NSCLC. J. Thorac. Oncol. 14(8), 1378–1389. https://doi.org/10.1016/j.jtho.2019.04.007 (2019).'}, {'Citation': 'Jin, C. et al. Commensal microbiota promote lung cancer development via gammadelta T cells. Cell 176(5), 998–1013. https://doi.org/10.1016/j.cell.2018.12.040 (2019).'}, {'Citation': 'Quast, C. et al. The SILVA ribosomal RNA gene database project: Improved data processing and web-based tools. Nucleic Acids Res. 41(Database issue), D590–D596. https://doi.org/10.1093/nar/gks1219 (2013).'}, {'Citation': 'Galperin, M. Y. et al. Microbial genome analysis: The COG approach. Brief. Bioinform. 20(4), 1063–1070. https://doi.org/10.1093/bib/bbx117 (2019).'}, {'Citation': 'Bolger, A. M., Lohse, M. & Usadel, B. Trimmomatic: A flexible trimmer for Illumina sequence data. Bioinformatics 30(15), 2114–2120. https://doi.org/10.1093/bioinformatics/btu170 (2014).'}, {'Citation': 'Reyon, D. et al. FLASH assembly of TALENs for high-throughput genome editing. Nat. Biotechnol. 30(5), 460–465. https://doi.org/10.1038/nbt.2170 (2012).'}, {'Citation': 'Hall, M. & Beiko, R. G. 16S rRNA gene analysis with QIIME2. Methods Mol. Biol. (Clifton, N.J.) 1849, 113–129. https://doi.org/10.1007/978-1-4939-8728-3_8 (2018).'}, {'Citation': 'Rognes, T. et al. VSEARCH: A versatile open source tool for metagenomics. PeerJ 4, e2584. https://doi.org/10.7717/peerj.2584 (2016).'}, {'Citation': 'Yin, Y. et al. Progress in the investigation of the firmicutes/bacteroidetes ratio as a potential pathogenic factor in ulcerative colitis. J. Med. Microbiol. 74(1), 10–1099. https://doi.org/10.1099/jmm.0.001966 (2025).'}, {'Citation': 'Yamada, M. et al. Characterization of gut microbiota dysbiosis in breast cancer patients. Breast Cancer (Tokyo, Japan) 33, 10–1007. https://doi.org/10.1007/s12282-025-01782-8 (2025).'}, {'Citation': 'Sadeghi, M., Haghshenas, B. & Nami, Y. Bifidobacterium exopolysaccharides: New insights into engineering strategies, physicochemical functions, and immunomodulatory effects on host health. Front. Microbiol. 15, 1396308. https://doi.org/10.3389/fmicb.2024.1396308 (2024).'}, {'Citation': 'Rahimi-Kolour, H. et al. Microbiota-driven epigenetic modifications in gastrointestinal cancer: Implications for pathogenesis and therapeutic strategies. World J. Microbiol. Biotechnol. 41(8), 288. https://doi.org/10.1007/s11274-025-04457-w (2025).'}, {'Citation': 'Lukic, I. et al. Antidepressants affect gut microbiota and Ruminococcus flavefaciens is able to abolish their effects on depressive-like behavior. Transl. Psychiatry 9(1), 133. https://doi.org/10.1038/s41398-019-0466-x (2019).'}, {'Citation': 'Strouse, C., Mangalam, A. & Zhang, J. Bugs in the system: Bringing the human microbiome to bear in cancer immunotherapy. Gut Microbes 10(2), 109–112. https://doi.org/10.1080/19490976.2018.1511665 (2019).'}, {'Citation': 'Chuang, H. H. et al. Different associations between tonsil microbiome, chronic tonsillitis, and intermittent hypoxemia among obstructive sleep apnea children of different weight status: A pilot case-control study. J. Pers. Med. https://doi.org/10.3390/jpm11060486 (2021).'}, {'Citation': 'Moiseenko, F. et al. Interconnection of gut microbiome and efficacy of immune checkpoint inhibitors in inoperable non-small-cell lung cancer. Int. J. Mol. Sci. 26(16), 7758. https://doi.org/10.3390/ijms26167758 (2025).'}, {'Citation': 'Porras, A. M. et al. Geographic differences in gut microbiota composition impact susceptibility to enteric infection. Cell Rep. 36(4), 109457. https://doi.org/10.1016/j.celrep.2021.109457 (2021).'}, {'Citation': 'Liu, F. et al. Dysbiosis of the gut microbiome is associated with tumor biomarkers in lung cancer. Int. J. Biol. Sci. 15(11), 2381–2392. https://doi.org/10.7150/ijbs.35980 (2019).'}, {'Citation': 'Carbone, C. et al. Lung and gut microbiota as potential hidden driver of immunotherapy efficacy in lung cancer. Mediators Inflamm. 2019, 7652014. https://doi.org/10.1155/2019/7652014 (2019).'}, {'Citation': 'Jordan, C. K. I. et al. Symbiotic Firmicutes establish mutualism with the host via innate tolerance and resistance to control systemic immunity. Cell Host Microbe. 31(9), 1433–1449. https://doi.org/10.1016/j.chom.2023.07.008 (2023).'}, {'Citation': 'Ma, X. et al. Sodium butyrate modulates gut microbiota and immune response in colorectal cancer liver metastatic mice. Cell Biol. Toxicol. 36(5), 509–515. https://doi.org/10.1007/s10565-020-09518-4 (2020).'}, {'Citation': 'Silva, Y. P., Bernardi, A. & Frozza, R. L. The role of short-chain fatty acids from gut microbiota in gut–brain communication. Front. Endocrinol. (Lausanne) 11, 25. https://doi.org/10.3389/fendo.2020.00025 (2020).'}, {'Citation': 'Biggs, M. B. et al. Systems-level metabolism of the altered Schaedler flora, a complete gut microbiota. ISME J. 11(2), 426–438. https://doi.org/10.1038/ismej.2016.130 (2017).'}, {'Citation': 'Wan, X. Z. et al. Anti-diabetic activity of PUFAs-rich extracts of Chlorella pyrenoidosa and Spirulina platensis in rats. Food Chem. Toxicol. 128, 233–239. https://doi.org/10.1016/j.fct.2019.04.017 (2019).'}, {'Citation': 'Ju, T. et al. Defining the role of Parasutterella, a previously uncharacterized member of the core gut microbiota. ISME J. 13(6), 1520–1534. https://doi.org/10.1038/s41396-019-0364-5 (2019).'}, {'Citation': 'Li, Y. et al. Alterations in the gut microbiota of patients with esophageal squamous cell carcinoma: A cross-sectional study conducted in a high-incidence region of China. Int. J. Gen. Med. 18, 6507–6522. https://doi.org/10.2147/IJGM.S541736 (2025).'}, {'Citation': 'Gerbec, Z. J. et al. Identification of intratumoral bacteria that enhance breast tumor metastasis. MBio 16(3), e359524. https://doi.org/10.1128/mbio.03595-24 (2025).'}, {'Citation': 'Li, W. et al. Structural changes of gut microbiota in Parkinson’s disease and its correlation with clinical features. Sci. China Life Sci. 60(11), 1223–1233. https://doi.org/10.1007/s11427-016-9001-4 (2017).'}, {'Citation': 'Yamamoto, K. et al. Influence of proton pump inhibitors on microbiota in chronic liver disease patients. Hepatol. Int. 13(2), 234–244. https://doi.org/10.1007/s12072-019-09932-9 (2019).'}, {'Citation': 'Menard, S. et al. Lactic acid bacteria secrete metabolites retaining anti-inflammatory properties after intestinal transport. Gut 53(6), 821–828. https://doi.org/10.1136/gut.2003.026252 (2004).'}, {'Citation': 'Wang, X. et al. Colorectal cancer in Lynch syndrome families: Consequences of gene germline mutations and the gut microbiota. Orphanet J. Rare Dis. 20(1), 30. https://doi.org/10.1186/s13023-025-03543-4 (2025).'}], 'ReferenceList': []}], 'History': [DictElement({'Year': '2026', 'Month': '1', 'Day': '20'}, attributes={'PubStatus': 'received'}), DictElement({'Year': '2026', 'Month': '4', 'Day': '8'}, attributes={'PubStatus': 'accepted'}), DictElement({'Year': '2026', 'Month': '4', 'Day': '19', 'Hour': '13', 'Minute': '11'}, attributes={'PubStatus': 'medline'}), DictElement({'Year': '2026', 'Month': '4', 'Day': '19', 'Hour': '13', 'Minute': '11'}, attributes={'PubStatus': 'pubmed'}), DictElement({'Year': '2026', 'Month': '4', 'Day': '18', 'Hour': '23', 'Minute': '16'}, attributes={'PubStatus': 'entrez'})], 'PublicationStatus': 'aheadofprint', 'ArticleIdList': [StringElement('42000796', attributes={'IdType': 'pubmed'}), StringElement('10.1038/s41598-026-48560-w', attributes={'IdType': 'doi'}), StringElement('10.1038/s41598-026-48560-w', attributes={'IdType': 'pii'})]}}]}

In [5]:
print(paper.keys())

dict_keys(['PubmedBookArticle', 'PubmedArticle'])

In [6]:
print(paper['PubmedArticle'][0].keys())

dict_keys(['MedlineCitation', 'PubmedData'])

In [7]:
print(paper['PubmedArticle'][0]['MedlineCitation'].keys())

dict_keys(['OtherAbstract', 'CitationSubset', 'GeneralNote', 'SpaceFlightMission', 'OtherID', 'InvestigatorList', 'KeywordList', 'PMID', 'DateRevised', 'Article', 'MedlineJournalInfo', 'CoiStatement'])

In [8]:
print(paper['PubmedArticle'][0]['PubmedData'].keys())

dict_keys(['ReferenceList', 'History', 'PublicationStatus', 'ArticleIdList'])

In [9]:
print(paper['PubmedArticle'][0]['MedlineCitation']['Article'].keys())

dict_keys(['ELocationID', 'Language', 'ArticleDate', 'Journal', 'ArticleTitle', 'Abstract', 'AuthorList', 'PublicationTypeList'])

In [10]:
title = paper['PubmedArticle'][0]['MedlineCitation']['Article']['ArticleTitle']
print(title)

Exploring the characteristics of gut microbiome changes in lung cancer patients and healthy controls.

In [11]:
pmid = paper['PubmedArticle'][0]['MedlineCitation']['PMID']
print(pmid)

42000796

In [12]:
abstract = paper['PubmedArticle'][0]['MedlineCitation']['Article']['Abstract']
print(abstract)

{'AbstractText': ['Lung cancer is among the most prevalent and lethal malignant neoplasms worldwide. Although the role of the pulmonary microbiome in the pathogenesis of lung cancer has been examined, the structure, diversity, and composition of the gut microbiome in lung cancer remain largely unclear. The present study is chiefly concerned with the analysis of the characteristics and alterations of the gut microbiome in lung cancer patients and healthy individuals, and with the exploration of potential characteristic gut microbiome in lung cancer patients. Stool samples were collected from 40 patients with lung cancer and 20 healthy controls at the Lung Cancer Center of West China Hospital, Sichuan University. The samples were analysed using 16S rRNA gene amplicon sequencing to investigate differences in the relative and absolute abundance, diversity, and functionality of the gut microbiome between the two groups. The predominant gut microbiome communities in lung cancer patients and healthy controls were found to comprise Bacteroidetes, Firmicutes, Proteobacteria, and Actinobacteria. The F/B (Firmicutes/Bacteroidetes) ratio in the lung cancer group (0.73) was lower than that in the healthy control group (0.96). We found that there was no significant difference in α-diversity between LC patients and the control group (p\u2009>\u20090.05), whereas β-diversity of the gut microbiome revealed differences in microbial community structure between the patient and control groups (stress\u2009<\u20090.2). The healthy controls exhibited higher abundances of Bacteroidetes and Firmicutes as dominant bacterial groups, whereas the characteristic bacterial groups in lung cancer patients were the Ruminococcus_gnavus_group and the Prevotellaceae NK3B31 group. Studies have demonstrated that the gut microbiome of patients with lung cancer patients undergoes changes, and characteristic gut microbiome profiles may serve as potential diagnostic markers for lung cancer. Furthermore, we have revealed that impairments in normal gut microbiome function may be associated with the development and progression of lung cancer, providing valuable insights for the early prevention, diagnosis, and targeted intervention of lung cancer.'], 'CopyrightInformation': '© 2026. The Author(s).'}

In [17]:
abstract = paper['PubmedArticle'][0]['MedlineCitation']['Article']['Abstract'].keys()
print(abstract)

dict_keys(['AbstractText', 'CopyrightInformation'])

In [13]:
#One record for start 
papers_data = []

article = paper['PubmedArticle'][0]

record = {
    'PMID':str(article['MedlineCitation']['PMID']),
    'Title':str(article['MedlineCitation']['Article']['ArticleTitle'])
}

record

{'PMID': '42000796',
 'Title': 'Exploring the characteristics of gut microbiome changes in lung cancer patients and healthy controls.'}

In [14]:
papers_data.append(record)
papers_data

[{'PMID': '42000796',
  'Title': 'Exploring the characteristics of gut microbiome changes in lung cancer patients and healthy controls.'}]

In [15]:
df = pd.DataFrame(papers_data)
df.head()

       PMID                                              Title
0  42000796  Exploring the characteristics of gut microbiom...

In [16]:
papers_data=[]

for pmid in pmids:
    try:
        handle = Entrez.efetch(
        db='pubmed',
        id = pmid,
        rettype = 'abstract',
        retmode = 'xml')

        paper = Entrez.read(handle)
        article = paper['PubmedArticle'][0]
        record = {
        'PMID':str(article['MedlineCitation']['PMID']),
        'Title':str(article['MedlineCitation']['Article']['ArticleTitle'])}

        papers_data.append(record)
    
    except Exception as e:
        print(f"Failed pmid: {pmid} with exception: {e}")
    

df = pd.DataFrame(papers_data)
df.head()
#len(df)

       PMID                                              Title
0  42000796  Exploring the characteristics of gut microbiom...
1  40057669  Regulatory, Translational, and Operational Con...
2  39609902  Diagnostic potential of salivary microbiota in...
3  38501000  Comprehensive analysis of ADGRE5 gene in human...
4  38456253  Association of PD-L1 expression with driver ge...

In [21]:
abstract_list = article['MedlineCitation']['Article']['Abstract']['AbstractText']
print(type(abstract_list))
print(len(abstract_list))

<class 'list'>
1